
# triger workflow events
on: 
  push:
    
jobs:
  update-files:
    runs-on: ubuntu-20.04
    name: Update file content
    steps:
        #This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout
        uses: actions/checkout@v3                      
        
      - name: update files
        id: update
        uses: sashosotirov/hw4@main
        with:
          remote-repo: kubernetes_wildfly
          remote-owner: sashosotirov
          remote-file: README.md
          current-file: README.md
          remoteToken: ${{ secrets.GH_PAT }}
          Token: ${{ secrets.GITHUB_TOKEN}}
          
      